name: Python Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests psutil pypdf pyautogui xvfbwrapper
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Flake8 (Linting) on all Python files
        continue-on-error: true
        run: |
          echo "Running flake8 linting..."
          find . -name "*.py" -print0 | xargs -0 flake8 --count --select=E9,F63,F7,F82 --show-source --statistics || true
          find . -name "*.py" -print0 | xargs -0 flake8 --count --max-complexity=10 --max-line-length=88 --statistics || true

      - name: Fix Xauthority Issue
        run: |
          sudo touch /home/runner/.Xauthority
          sudo chown $(whoami):$(whoami) /home/runner/.Xauthority

      - name: Ensure Python Files Are Readable
        run: chmod -R +r .

      - name: Create conftest.py for missing fixtures
        run: |
          cat << 'EOF' > conftest.py
          import os
          import pytest

          @pytest.fixture
          def directory():
              return os.getcwd()

          @pytest.fixture
          def script_path():
              return os.path.join(os.getcwd(), "something_test.py")
          EOF

      - name: Debug Python File Detection
        run: |
          echo "Listing all Python files:"
          find . -name "*.py"

      - name: Debug Pytest Collection
        run: |
          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH set to: $PYTHONPATH"
          pytest --collect-only --capture=no -o debug=true -o log_cli=true --log-level=DEBUG .

      - name: Run Pytest (Testing) on something_test.py
        env:
          PASTEBIN_API: ${{ secrets.PASTEBIN_API }}
          DISPLAY: ":99"
          PYTHONIOENCODING: "utf-8"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          Xvfb :99 -screen 0 1024x768x16 -nolisten tcp -noreset &
          export DISPLAY=":99"
          sleep 3
          pytest -v --tb=short --capture=no ./something_test.py
