name: Python Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests psutil pypdf pyautogui xvfbwrapper
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Flake8 (Linting) on all Python files
        continue-on-error: true
        run: |
          echo "Running flake8 linting..."
          find . -name "*.py" -print0 | xargs -0 flake8 --count --select=E9,F63,F7,F82 --show-source --statistics || true
          find . -name "*.py" -print0 | xargs -0 flake8 --count --max-complexity=10 --max-line-length=88 --statistics || true

      - name: Fix Xauthority Issue
        run: |
          sudo touch /home/runner/.Xauthority
          sudo chown $(whoami):$(whoami) /home/runner/.Xauthority

      - name: Run Pytest (Testing) on all Python files
        env:
          PASTEBIN_API: ${{ secrets.PASTEBIN_API }}
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1024x768x16 -nolisten tcp -noreset &
          export DISPLAY=":99"
          sleep 3
          find . -name "test_*.py" -o -name "*_test.py"
          pytest -v --tb=short --debug
